# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1703c645aecd659b62cf8885433efa7eb80e9e894f821f1507ad85833a38327e634635bcfc43f3ecb2d1f0ffbdd4e48d4b56499ba73e5d083f201d5be67d4965

test:
  secret_key_base: 06c1c172d3607dff52b45ff8543c2ae9c996455a3c8a5be78420c0b1e9e366f0815ddfddbd2a51f9ddecc92fd41c89024eb26d29f8f9c38b34e8109d64d1781c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
